import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - don't use client-side code here (no `window`, etc.).

// Any docs folder can be a sidebar. This one is auto-generated from the
// sidebar_position front-matter in each doc file.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
